name = "DynamicBinding"
uuid = "6bdceb15-c946-478d-879d-2d3f90816119"
authors = ["Pepijn de Vos <pepijndevos@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]